  #server.port: 9090

spring:
    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/shop
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver

        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: SELECT 1 FROM DUAL
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxPoolPreparedStatementPerConnectionSize: 20
#        filters: stat,wall,log4j
#        connectionProperties: druid.stat.mergeSql: true;druid.stat.slowSqlMillis: 5000
#        useGlobalDataSourceStat: true

#JPA Configuration:
    jpa:
        database: MYSQL
         # Show or not log for each sql query
        show-sql: false
        generate-ddl: true
        # Hibernate ddl auto (create, create-drop, update)
        hibernate.ddl-auto: update
        #spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        #spring.jpa.database: org.hibernate.dialect.MySQL5InnoDBDialect
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

#    mvc:
#        static-path-pattern: /**
#        view:
#            prefix: /WEB-INF/view/
#            suffix: .jsp
#    resources:
#            static-locations: classpath:/META-INF/resources/, classpath:/resources/,classpath:/static/,file:${web.upload-path}
#
#thymeleaf start
    thymeleaf:
         mode: HTML5
         encoding: UTF-8
         #content-type: text/html
         #开发时关闭缓存,不然没法看到实时页面
         cache: false
         prefix: classpath:/
#         suffix: .html
#thymeleaf end

